// Decompiled with JetBrains decompiler
// Type: ObjectLayer
// Assembly: Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
// MVID: D13CBB0B-55A9-4EF0-9BB5-5C2436A6B8EE
// Assembly location: D:\dev\OniMod\Assembly-CSharp.dll

public enum ObjectLayer
{
  Minion,
  Building,
  Backwall,
  Pickupables,
  Canvases,
  Plants,
  FillPlacer,
  DigPlacer,
  MopPlacer,
  FoundationTile,
  PlasticTile,
  ReplacementTile,
  GasConduit,
  GasConduitTile,
  ReplacementGasConduit,
  GasConduitConnection,
  LiquidConduit,
  LiquidConduitTile,
  ReplacementLiquidConduit,
  LiquidConduitConnection,
  SolidConduit,
  SolidConduitTile,
  ReplacementSolidConduit,
  SolidConduitConnection,
  LadderTile,
  ReplacementLadder,
  Wire,
  WireTile,
  ReplacementWire,
  WireConnectors,
  LogicGate,
  LogicWire,
  LogicWireTile,
  ReplacementLogicWire,
  TravelTube,
  TravelTubeTile,
  ReplacementTravelTube,
  TravelTubeConnection,
  AttachableBuilding,
  Gantry,
  Mover,
  Rover,
  Critter,
  ReplacementBackwall,
  NumLayers,
}
